apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name:  go-app2
          image: gotodengo89/go_app2
          ports:
            - containerPort: 7777
          env:
            - name: GREET
              valueFrom:
                configMapKeyRef:
                  name: app2-config
                  key: greeting
